#!/bin/sh -e

patch -p1 < muon.patch

# This needs investigation.
sed 's/gnu99/gnu11/' meson.build > _
mv -f _ meson.build

export CFLAGS="$CFLAGS -fPIC"

# Build fails with clang due to -Werror (forced on) and
# -Wunused-command-line-argument which is triggered by.
# the below CFLAGS.
export CFLAGS="-Wno-unused-command-line-argument $CFLAGS"

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlibexecdir=/usr/lib \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    output

ninja -C output
muon  -C output install
