#!/bin/sh -e

# TODO send patch
sed "s/'\(true\|false\)'/\1/" meson_options.txt > _
mv -f _ meson_options.txt

muon setup \
    -Dprefix=/usr \
    -Dtests=disabled \
    -Ddocumentation=disabled \
    output

ninja -C output
muon  -C output install
